[destination.redshift.credentials]
host = "your-redshift-cluster.region.redshift.amazonaws.com" # ändra
port= 5439 # kan va annorlunda?
database= "your_db" # ändra
user = "your_user" # ändra
password = "your_password"